  name: Run end to end tests for prometheus-operator using a virtual kubernetes cluster

  on:
    push:
      branches:
      - master

  env:
    LOFT_VERSION: '1.7.2'
    LOFT_URL: 'https://loft.l3v.co/'
    LOFT_USERNAME: 'admin'
    LOFT_ACCESS_KEY: ${{ secrets.LOFT_ACCESS_KEY }}
    VCLUSTERNAME: 'ci'
  jobs:
    setup-test-publish-deploy:
      name: Setup, test, publish, deploy
      runs-on: ubuntu-20.04

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl

      - name: Setup Loft
        run: |
          curl -sfLo ./loft https://github.com/loft-sh/loft/releases/download/v$LOFT_VERSION/loft-linux-amd64
          chmod +x ./loft

      - name: Login to Loft instance
        run: |
          ./loft login --insecure $LOFT_URL --username $LOFT_USERNAME --access-key $LOFT_ACCESS_KEY

      - name: Loft delete vcluster
        run: |
          ./loft delete vcluster $VCLUSTERNAME

      - name: Create virtual cluster
        run: |
          ./loft create vcluster $VCLUSTERNAME

      - name: Loft use vcluster
        run: |
          ./loft use vcluster $VCLUSTERNAME --print > kube_config

      - name: Get all pods
        run: |-
          ./kubectl --insecure-skip-tls-verify=true --kubeconfig='kube_config' get all --all-namespaces

      - name: Loft delete vcluster
        run: |
          ./loft delete vcluster $VCLUSTERNAME